core:
  metrics:
    apm_server:
      server_url: null
  redis:
    nonpersistent:
      host: localhost
      port: 6379
    persistent:
      host: localhost
      port: 6379
datastore:
  hosts: ["localhost:9200"]
filestore:
  cache:
    - file:///var/cache/assemblyline/
  storage:
    - file:///var/cache/assemblyline/
logging:
  log_as_json: false
